version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: db_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: master123
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  api:
    depends_on:
      - db
    container_name: api
    ports:
      - 3000:3000
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - .env
    volumes:
      - ./:/app

volumes:
  db_data:
